### ISSUE TITLE
Unable to reproduce the results in the paper

### ISSUE THREAD

**Issue by sshiningg** [Vadim200116/T-3DGS#1]
Thank you for your excellent work!
I experimented using the following command

`python train.py -s ./data/on-the-go/patio_high -m ./output/t-3dgs/on-the-go/patio_high --fps 2 --eval --resolution 8`

but I got the following result
<img width="167" alt="{80F2B910-4638-4B7C-B368-A3F58213D613}" src="https://github.com/user-attachments/assets/62d83939-69aa-4908-8bf2-bb7ad17b91f7">

During training, the depth loss was always 0. Can you provide the depth_params.json file for the dataset?

**Comment by Vadim200116** [comment]
Hi! I cloned this repo and trained on patio high scene with the same arguments as you and obtained metrics:
```
  SSIM :    0.8366932 [10/12 10:11:47]
  PSNR :   22.9985542 [10/12 10:11:47]
```
I think the problem was caused by the input data. Can you please clarify which way you obtained camera positions from the data?
In our work we used this [script](https://github.com/Vadim200116/T-3DGS/blob/main/convert.py) on all input images.
And also check how your input images are orginized? We assume that the image files have prefixes determining clean (clean), cluttered train data (clutter) and clean test data (extra). if ```--eval``` argument was passed, than the model will be trained on clutter images and evaluated on extra.

About depth loss. This depth loss is inherited from original gaussian splatting repo. It's not connected with what we call depth loss in our work. This thing is named tv (total variation loss) in our code. This tv loss is enabled by default with ```--lambda_tv``` flag. In our work we do not use depth loss from original repo, so that's okay that it is zero.

**Comment by sshiningg** [comment]
The data I used is the undistorted version here
https://huggingface.co/datasets/jkulhanek/nerfonthego-undistorted/tree/main

I didn't rename the original image with different prefixs, I put the test image name in sparse/0/test.txt

Thank you for your guidance. I will run convert.py and experiment again.

**Comment by Vadim200116** [comment]
Okay. Also I want to mention that we used data from original repo https://rwn17.github.io/nerf-on-the-go/ . So it would be better to use it if you care about results reproducibility
